services:
  app:
    build: .
    restart: always
    command: bash -c "cd app && make dev"
    ports:
      - 8080:8080

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
