services:
  app:
    image: pavel123321/devops-for-programmers-project-74
    environment:
      DATABASE_NAME: ${DATABASE_NAME},
      DATABASE_USERNAME: ${DATABASE_USERNAME},
      DATABASE_PASSWORD: ${DATABASE_PASSWORD},
      DATABASE_PORT: ${DATABASE_PORT},
      DATABASE_HOST: ${DATABASE_HOST},
    build:
      context: .
      dockerfile: Dockerfile.production
    restart: always
    command: make test
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5