services:
  app:
    image: pavel123321/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    restart: always
    command: make test
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5